image: golang:latest

variables:
  REPO_NAME: gitlab.com/luizbranco/cyberbrain

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - go get ./...

stages:
    - test

format:
    stage: test
    script:
      - go vet ./...
      - go test -race ./...
