image: golang:latest

variables:
  GO111MODULE: "on"
  REPO_NAME: gitlab.com/luizbranco/cyberbrain

before_script:
  - go get ./...

stages:
    - test

format:
    stage: test
    script:
      - go vet ./...
      - go test -race ./...
