version: '3.5'

services:

  db:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cyberbrain
      POSTGRES_USER: cyberbrain
      POSTGRES_PASSWORD: s3cr3t
    networks:
      - backend

  server:
    image: cyberbrain/server:dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ENVIRONMENT: dev
      DATABASE_URL: "postgres://cyberbrain:s3cr3t@db:5432/cyberbrain?sslmode=disable"
      SESSION_SECRET: S5L56UH4TKQNYJMNK486WLH7E4MQRV26
      HASHID_SALT: LXRQSJ68ZUXMEQOP2E0T7QJW43GGC3FA
      AWS_ID: ${AWS_ID}
      AWS_BUCKET: ${AWS_BUCKET}
      BLITLINE_ID: ${BLITLINE_ID}
      BLITLINE_CALLBACK_URL: ${BLITLINE_CALLBACK_URL}
      PIIO_DOMAIN: ${PIIO_DOMAIN}
      PIIO_ID: ${PIIO_ID}
    networks:
      - backend

volumes:
  db-data:
    name: cyberbrain-db-data

networks:
  backend:
